// src/lib/apps/dossier/utils/blockRender.js
// The read half of the shared renderer (merge doc §11, decision D10).
//
// Composer and the P3 public reader must render from ONE definition, so that
// what the author sees is what the recipient gets. That is achieved by both
// modes going through `buildExtensions()` and the `.dossier-prose` stylesheet
// in components/BlockContent.svelte — the only difference is whether a live
// Editor is attached (mode 'edit') or static HTML is generated (mode 'read').
//
// Nothing here touches the DB or Svelte, so the P3 reader can call it from a
// snapshot without loading any authoring code.

import { generateHTML } from '@tiptap/core';
import DOMPurify        from 'dompurify';
import { getLogger }    from '$lib/utils/logger';
import { buildExtensions, EMPTY_DOC } from './blockSchema.js';
import { isProxyUrl, assetIsMissing } from './assetPreview.js';
import {
  resolveEmbedRender, firstParagraphText, EMBED_NOTE_TEXT, MAX_EMBED_DEPTH,
} from './embedGuard.js';
import { renderDatasetTableHtml, renderMissingDatasetHtml } from './datasetRender.js';
import { renderSheetPreviewHtml } from './sheetPreview.js';

const logger = getLogger('dossierBlockRender');

// A Dossier-specific allow-list rather than the shared $lib/utils/sanitizeHtml:
// that one is documented as matching StarterKit output, and this schema adds
// callout and toggle. Their styling and every block anchor ride on data-*
// attributes, so those must survive — hence ALLOW_DATA_ATTR is explicit rather
// than left to DOMPurify's default.
const ALLOWED_TAGS = [
  'p', 'br', 'hr',
  'h1', 'h2', 'h3',
  'blockquote', 'ul', 'ol', 'li',
  'code', 'pre',
  'strong', 'em', 's', 'b', 'i', 'u',
  'a', 'span', 'div',
  // Asset previews (P1 step 2). `img` only — neither `iframe` nor `object` is
  // admitted. PDFs render as an open-in-new-tab card rather than an embedded
  // viewer (see assetPreview.js), which means no frame primitive needs to
  // exist in the one feature built to be handed to an outsider.
  'img',
  // An embedded dataset renders as a real table (P2 step 2). The markup is
  // generated by datasetRender.js, which escapes every author value itself.
  'table', 'thead', 'tbody', 'tr', 'th', 'td',
  // A long email body folds into a <details> beneath its row (P2/P3). The
  // embedded-table path injects after sanitising, so this is belt and braces —
  // but a renderer that survives the sanitiser is one less trap for whoever
  // next routes table HTML through it.
  'details', 'summary',
];

const ALLOWED_ATTR = ['href', 'target', 'rel', 'class', 'src', 'alt', 'title', 'style'];

/**
 * Sanitise generated block HTML before it reaches {@html}.
 *
 * The HTML is produced from our own schema, so this is defence in depth rather
 * than the primary control — but a pack is the one thing in this portal built
 * to be handed to an outsider, so the render path is belt and braces.
 */
export function sanitizeBlockHtml(html, { assetBase = '' } = {}) {
  if (typeof html !== 'string' || html === '') return '';
  // DOMPurify needs a window; during SSR there is nothing to render into.
  if (typeof window === 'undefined') return html;

  // Confine <img> to this app's own file proxy, so a stored block cannot point
  // at an external URL — which would leak a reader's IP to a third party the
  // moment a published pack is opened.
  const hook = (node) => {
    const tag = node.tagName?.toLowerCase();
    if (tag !== 'img') return;
    const src = node.getAttribute('src');
    // Two shapes are admissible: this app's media proxy (the author's view),
    // and the token-scoped base a published pack renders with. Both are
    // same-origin paths this code generated; anything else goes.
    const ours = assetBase ? String(src ?? '').startsWith(assetBase) : false;
    if (!ours && !isProxyUrl(src)) node.remove();
  };

  DOMPurify.addHook('afterSanitizeAttributes', hook);
  try {
    return DOMPurify.sanitize(html, {
      ALLOWED_TAGS,
      ALLOWED_ATTR,
      ALLOW_DATA_ATTR: true,
      ADD_ATTR: ['target', 'rel'],
    });
  } finally {
    // DOMPurify hooks are global; leaving this one installed would silently
    // change every other sanitise call in the app.
    DOMPurify.removeHook('afterSanitizeAttributes');
  }
}

/**
 * Render stored ProseMirror JSON to sanitised HTML.
 *
 * Returns '' for anything unrenderable rather than throwing: stored JSON that
 * no longer matches the schema must not take a whole page — or a published
 * pack — down with it. The caller distinguishes "empty" from "broken".
 *
 * @param {object} blocks - dossier_docs.blocks
 * @returns {string}
 */
export function renderBlocksToHtml(blocks, opts = {}) {
  const json = blocks && typeof blocks === 'object' && blocks.type ? blocks : EMPTY_DOC;
  try {
    // assetBase decides where a file's bytes come from — empty for the author
    // (this app's media proxy), token-scoped for a published pack's recipient.
    const html = sanitizeBlockHtml(
      generateHTML(json, buildExtensions({ assetBase: opts.assetBase ?? '' })),
      opts);
    return expandEmbeds(
      resolveDatasetEmbeds(resolveSheetPreviews(resolveAssets(html, opts)), opts),
      opts);
  } catch (err) {
    logger('⚠ could not render blocks', err);
    return '';
  }
}

/**
 * The "resolve references" stage of the pipeline (spec 2 §11).
 *
 * Embed nodes render only a placeholder, because a declarative renderHTML has
 * no access to the other pages. This fills each one — applying the cycle and
 * depth guard first, and recursing through the SAME renderer so an embedded
 * page looks exactly like the real thing.
 *
 * A no-op when there are no pages to resolve against (the editor's own live
 * view) or no DOM (SSR), so callers never have to check.
 *
 * @param {string} html
 * @param {{ docs?: object[], ancestry?: string[], maxDepth?: number }} opts
 */
function expandEmbeds(html, { docs = [], ancestry = [], maxDepth = MAX_EMBED_DEPTH } = {}) {
  if (!html || typeof document === 'undefined') return html;
  // No pages to resolve against means the CALLER supplied no resolver — the
  // live editor, which fills placeholders with its own node view. It does not
  // mean every target is deleted, and treating it that way would stamp
  // "this page no longer exists" over every embed in the editor.
  if (!docs.length) return html;

  const host = document.createElement('div');
  host.innerHTML = html;

  const placeholders = host.querySelectorAll('div[data-embed-doc]');
  if (!placeholders.length) return html;

  const byId = new Map(docs.map(d => [d.id, d]));

  for (const node of placeholders) {
    const targetId = node.getAttribute('data-embed-doc');
    const target   = byId.get(targetId);
    const title    = target?.title || node.getAttribute('data-embed-title') || 'Untitled page';

    const decision = resolveEmbedRender({
      requested: node.getAttribute('data-embed-mode'),
      targetId,
      ancestry,
      exists:    Boolean(target),
      maxDepth,
    });

    node.setAttribute('data-embed-rendered', decision.mode);
    if (decision.note) node.setAttribute('data-embed-note', decision.note);

    const heading = `<div class="dossier-embed-title">${escapeHtml(title)}</div>`;

    if (decision.mode === 'full') {
      // Recurse with this page pushed onto the ancestry — that is what the
      // cycle guard reads on the way back down.
      const inner = renderBlocksToHtml(target.blocks, {
        docs, ancestry: [...ancestry, targetId], maxDepth,
      });
      node.innerHTML = `${heading}<div class="dossier-embed-body">${inner}</div>`;
      continue;
    }

    if (decision.mode === 'summary') {
      const summary = firstParagraphText(target.blocks);
      node.innerHTML = heading
        + `<div class="dossier-embed-summary">${escapeHtml(summary || 'This page is empty.')}</div>`;
      continue;
    }

    const note = decision.note ? EMBED_NOTE_TEXT[decision.note] : '';
    node.innerHTML = heading
      + (note ? `<div class="dossier-embed-note">${escapeHtml(note)}</div>` : '');
  }

  return host.innerHTML;
}

/**
 * Resolve each asset against the pack's shelf: mark the ones whose file has
 * gone, and give the rest their file's DESCRIPTION.
 *
 * The description is looked up live rather than copied onto the block, so
 * editing it once updates every page that shows the file — the same
 * reference-not-copy rule the rest of the app follows.
 *
 * Without this the block renders a normal image or download card pointing at a
 * file that 404s — the reference looks healthy right up until someone clicks
 * it, which is the worst possible moment for a recipient to find out.
 *
 * Skipped entirely when no shelf is supplied: absence can only be proven
 * against an actual list.
 */
function resolveAssets(html, { files } = {}) {
  if (!html || typeof document === 'undefined') return html;
  if (!Array.isArray(files) || !files.length) return html;

  const host = document.createElement('div');
  host.innerHTML = html;

  const assets = host.querySelectorAll('div[data-asset]');
  if (!assets.length) return html;

  const byId = new Map(files.map(f => [f.id, f]));
  let changed = false;

  for (const node of assets) {
    const documentId = node.getAttribute('data-document_id');
    const name = node.getAttribute('data-filename') || 'File';

    if (assetIsMissing(documentId, files)) {
      node.setAttribute('data-kind', 'missing');
      node.innerHTML =
        '<div class="dossier-asset-card dossier-asset-gone">'
        + '<span class="dossier-asset-icon">⚠</span>'
        + `<span class="dossier-asset-name">${escapeHtml(name)}`
        + ' — this file is no longer available</span></div>';
      changed = true;
      continue;
    }

    // The author's choice, carried on the block (assetNode.js `show_description`).
    // Absent means true, so blocks placed before the control existed keep
    // showing what they always showed.
    const description = node.getAttribute('data-show_description') === 'false'
      ? '' : byId.get(documentId)?.description;
    if (description) {
      node.insertAdjacentHTML('beforeend',
        `<div class="dossier-asset-description">${escapeHtml(description)}</div>`);
      changed = true;
    }
  }

  return changed ? host.innerHTML : html;
}

/**
 * Put a spreadsheet's snapshot above its card.
 *
 * The snapshot rides on the block as `data-sheet_preview` (see assetNode.js for
 * why it is cached rather than fetched), so this stage needs nothing from the
 * caller and always runs — including in a P3 published pack, which has no
 * server to ask.
 *
 * @param {string} html
 */
function resolveSheetPreviews(html) {
  if (!html || typeof document === 'undefined') return html;
  if (!html.includes('data-sheet_preview')) return html;

  const host = document.createElement('div');
  host.innerHTML = html;

  let changed = false;
  for (const node of host.querySelectorAll('div[data-sheet_preview]')) {
    // A missing file already replaced this block's contents; do not put a
    // table above a "no longer available" card.
    if (node.getAttribute('data-kind') === 'missing') continue;

    let preview = null;
    try { preview = JSON.parse(node.getAttribute('data-sheet_preview') ?? 'null'); }
    catch { continue; }              // corrupted attr → just the card

    const table = renderSheetPreviewHtml(preview, escapeHtml);
    if (!table) continue;
    node.insertAdjacentHTML('afterbegin', table);
    changed = true;
  }

  return changed ? host.innerHTML : html;
}

/**
 * Fill each embedded-table placeholder with the table itself.
 *
 * No cycle or depth guard is needed here, unlike page embeds: a table cannot
 * contain an embed, so the graph is one level deep by construction.
 *
 * Skipped when no tables are supplied — that means the caller gave no resolver,
 * not that every table has been deleted.
 */
function resolveDatasetEmbeds(
  html, { datasets = [], records = [], docs = [], files = [], assetBase = '' } = {},
) {
  if (!html || typeof document === 'undefined') return html;
  if (!datasets.length) return html;

  const host = document.createElement('div');
  host.innerHTML = html;

  const placeholders = host.querySelectorAll('div[data-embed-dataset]');
  if (!placeholders.length) return html;

  for (const node of placeholders) {
    const id = node.getAttribute('data-embed-dataset');
    const dataset = datasets.find(d => d.id === id);

    node.innerHTML = dataset
      // Row references travel here too: a chronology shown inside a page is the
      // same table, and dropping its links only when embedded would be an
      // arbitrary difference the author never asked for.
      ? renderDatasetTableHtml(dataset, records.filter(r => r.dataset_id === id),
          { links: { docs, files, assetBase } })
      : renderMissingDatasetHtml(node.getAttribute('data-embed-dataset-title'));
  }

  return host.innerHTML;
}

/** Titles and summaries are plain text and must not be able to inject markup. */
function escapeHtml(value) {
  const el = document.createElement('span');
  el.textContent = String(value ?? '');
  return el.innerHTML;
}

/**
 * Plain-text preview of a doc — for search snippets, list subtitles and the
 * revision history. Walks the JSON directly; no DOM required, so this one is
 * safe to call server-side.
 *
 * @param {object} blocks
 * @param {number} [limit]
 */
export function blocksToText(blocks, limit = 160) {
  const parts = [];

  const walk = (node) => {
    if (!node || parts.join(' ').length > limit) return;
    if (typeof node.text === 'string') parts.push(node.text);
    if (Array.isArray(node.content)) node.content.forEach(walk);
  };
  walk(blocks);

  const text = parts.join(' ').replace(/\s+/g, ' ').trim();
  return text.length > limit ? `${text.slice(0, limit).trimEnd()}…` : text;
}
