// src/lib/utils/statutoryRegisterData.js
//
// THE PERIODIC ACTIVITY REGISTER — every recurring check identified for a
// higher-risk residential building in England, from every source we hold.
// Data only; the logic that reads it is in statutoryTemplate.js.
//
// ── Sources merged here ─────────────────────────────────────────────────────
// · docs/requirements/BSA_Periodic_Activities_and_Checks.docx — the fullest
//   list, and the one that supplied the FSER regulation numbers (reg 4, 8, 11)
//   and the governance/BSA cycles. ⚠ It is written for **Lancaster House,
//   Manchester**, not Lonsdale House — the only supplied document that names a
//   building. Its building-specific §5 items (basement Acrow-prop monitoring,
//   fire-alarm coverage-gap monitoring, the stair-core regime) are NOT included
//   here: they are interim mitigations tied to that building's own open
//   findings, not a general register.
// · docs/requirements/Commercial_Landscape_and_Gaps.md §4.4 / §4.5 — our own
//   FSER cadence table and certificate register.
// · docs/inspection_user_guide.md — corroborates FSER reg 6.
//
// ⚠ THE REGULATION-NUMBER TRAP. The BSA documents cite **SI 2023/907** at
// reg 6 (MOR) and reg 10 (engagement strategy). Those are DIFFERENT regs 6 and
// 10 from the Fire Safety (England) Regulations 2022 ones below — same numbers,
// different instrument, unrelated subject. Never cross-reference the two.
//
// ⛔ DELIBERATELY EXCLUDED: PEEPs / PCFRAs. Decided 2026-09-10, reaffirmed
// after the Lancaster document listed them. Resident personal data stays out of
// this portal (Resident_System_Interface.md), and a PEEP is special-category
// health data about a named person. Do not re-add.
//
// ── The four fields that make an entry legible ──────────────────────────────
// `basis`         WHERE THE REQUIREMENT COMES FROM — see BASIS in the logic
//                 module. Legislation / standard / contract / management.
// `intervalBasis` whether the INTERVAL is set by that source ('stated') or is
//                 established practice around a qualitative duty ('practice').
// `handledBy`     WHICH SUB-APP deals with it today, or 'none' where nothing in
//                 the portal does. 'none' is the honest answer for several, and
//                 the register is more useful for saying so.
// `evidencedBy`   how the obligation library SCHEDULES it: an inspection walk,
//                 a maintenance job, or `null` where another app owns its own
//                 cycle and creating an obligation would duplicate it.
//
// A maintenance job does not require a contractor, so it is the route for any
// dated task with an owner — including desk reviews.

// ── When a requirement is WITHDRAWN ────────────────────────────────────────
// A repealed or superseded requirement is FLAGGED, never deleted:
//
//   supersededOn:   'YYYY-MM-DD'   the date it stopped being required
//   supersededBy:   'other_key'    the entry that replaced it, if one did
//   supersededNote: 'why'          the instrument that repealed it
//
// It stays in the register forever. Three reasons, and the third is the one
// that matters most:
//   1. Work done under it BEFORE that date is still valid evidence, and the
//      history report must still be able to describe what it was for.
//   2. An assessor looking at a 2027 report of 2026 work needs the requirement
//      to still exist to make sense of it.
//   3. Deleting the entry would strand every obligation carrying its
//      `template_key`, silently turning discharged work into an orphan.
//
// This is a fact about the LAW, not about this building — which is why it
// lives here in version control rather than in `statutory_exclusions`, where a
// second building would need its own row repeating it.

/** Defaults so an entry only states what is true of it. */
function entry(e) {
  return {
    maxIntervalDays: null,
    competencyRequired: null,
    retentionPeriodMonths: 36,
    trigger: null,
    frequencyDays: null,
    handlingNote: '',
    supersededOn: null,
    supersededBy: null,
    supersededNote: '',
    ...e,
  };
}

export const REGISTER = [

  // ══ 1 · Statutory fire safety ═══════════════════════════════════════════
  entry({
    key: 'fra_refresh',
    name: 'Fire risk assessment — refresh',
    description: 'Refresh the fire risk assessment and record it in full.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Regulatory Reform (Fire Safety) Order 2005, art 9',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Responsible person, via a competent fire risk assessor',
    competencyRequired: 'Competent fire risk assessor; third-party certificated (e.g. BAFE SP205) recommended for an HRB',
    evidenceRequired: 'Reviewed and dated FRA, recorded in full, with an action plan',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'The FRA itself is a Golden Thread document with its own review-due date.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always — art 9 applies to every building with common parts',
  }),
  entry({
    key: 'fra_action_plan_review',
    name: 'FRA action plan — review',
    description: 'Review progress against the fire risk assessment’s action plan and re-prioritise what is open.',
    group: 'fire_safety',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports BSA 2022 s.84 reasonable steps',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Meeting record and an updated action register',
    handledBy: 'management',
    handlingNote: 'FRA actions live as Management issues/actions; this is the recurring review of them.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'A fire risk assessment exists with open actions',
  }),
  entry({
    key: 'fser_communal_fire_doors',
    name: 'Fire door checks — communal doors',
    description: 'Check all fire doors in the common parts, including self-closing devices.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 10(2)',
    intervalBasis: 'stated',
    frequencyDays: 90,
    maxIntervalDays: 92,
    responsibleParty: 'Responsible person',
    competencyRequired: 'Person trained in fire door inspection; formal certification not required by the regulation',
    evidenceRequired: 'Dated check record per door, with defects and remedial action',
    handledBy: 'inspection',
    handlingNote: 'An inspection walk scoped to communal fire doors.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'fser_flat_entrance_doors',
    name: 'Fire door checks — flat entrance doors',
    description: 'Best endeavours to check every flat entrance door opening onto a common part.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 10(1)',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Responsible person',
    competencyRequired: 'Person trained in fire door inspection',
    evidenceRequired: 'Dated check record per door, plus a record of access attempts where entry was refused',
    handledBy: 'inspection',
    handlingNote: 'The walk’s “No access” outcome exists for this duty — best endeavours, evidenced.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building is over 11 metres and has flat entrance doors onto common parts',
  }),
  entry({
    key: 'fdis_scheme_inspection',
    name: 'Fire door inspection — certificated scheme round',
    description:
      'Third-party certificated fire door inspection. Distinct from the responsible person’s own reg 10 check: '
      + 'a different person, to a scheme standard, producing a per-door report.',
    group: 'fire_safety',
    basis: 'contract',
    statutoryRef: 'FDIS scheme; BS 8214',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Managing agent, commissioned to an FDIS inspector',
    competencyRequired: 'FDIS certificated inspector',
    evidenceRequired: 'Per-door inspection report',
    handledBy: 'maintenance',
    handlingNote: 'A contractor job; the report registers to the Golden Thread on completion.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'The building commissions scheme inspections in addition to its own checks',
  }),
  entry({
    key: 'fire_alarm_weekly_test',
    name: 'Fire alarm — weekly test',
    description: 'Operate one manual call point (a different one each week) and confirm the alarm sounds.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 5839-1, weekly testing by the user',
    intervalBasis: 'stated',
    frequencyDays: 7,
    maxIntervalDays: 7,
    responsibleParty: 'Responsible person or site staff',
    competencyRequired: 'Briefed site staff; no formal qualification required',
    evidenceRequired: 'Logbook entry naming the call point tested and the result',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a fire detection and alarm system',
  }),
  entry({
    key: 'fire_alarm_service',
    name: 'Fire alarm — periodic inspection and service',
    description: 'Periodic inspection and servicing of the fire detection and alarm system by a competent engineer.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 5839-1, periodic inspection and servicing',
    intervalBasis: 'stated',
    frequencyDays: 182,
    maxIntervalDays: 183,
    responsibleParty: 'Fire alarm service contractor',
    competencyRequired: 'Competent fire alarm engineer; BAFE SP203-1 certificated firm recommended',
    evidenceRequired: 'Servicing certificate listing devices tested and any non-compliances',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a fire detection and alarm system',
  }),
  entry({
    key: 'emergency_lighting_monthly',
    name: 'Emergency lighting — monthly function test',
    description: 'Short-duration function test of every emergency luminaire and exit sign.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 5266-1 / BS EN 50172, monthly function test',
    intervalBasis: 'stated',
    frequencyDays: 30,
    maxIntervalDays: 31,
    responsibleParty: 'Responsible person or site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Logbook entry per test, with any failed luminaires identified',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has emergency escape lighting',
  }),
  entry({
    key: 'emergency_lighting_annual',
    name: 'Emergency lighting — annual full-duration test',
    description: 'Full rated-duration discharge test (normally three hours), with luminaires recharged afterwards.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 5266-1, annual full-duration test',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Emergency lighting contractor',
    competencyRequired: 'Competent electrical contractor',
    evidenceRequired: 'Annual test certificate recording the duration achieved per luminaire',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has emergency escape lighting',
  }),
  entry({
    key: 'sprinkler_weekly_test',
    name: 'Suppression system — weekly test',
    description: 'Weekly test routine on the sprinkler or suppression system, including any pump run.',
    group: 'fire_safety',
    basis: 'contract',
    statutoryRef: 'LPC Rules; insurance policy condition',
    intervalBasis: 'stated',
    frequencyDays: 7,
    maxIntervalDays: 7,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff working to the system’s own test routine',
    evidenceRequired: 'Weekly test log with sign-off',
    handledBy: 'inspection',
    handlingNote: 'A weekly inspection walk; the insurer’s condition is what makes it binding.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a sprinkler or other fixed suppression system',
  }),
  entry({
    key: 'sprinkler_annual_service',
    name: 'Suppression system — annual service',
    description: 'Annual service and test of the sprinkler or residential suppression system.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 9251 (residential) / BS EN 12845; LPC Rules',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Suppression system contractor',
    competencyRequired: 'Competent sprinkler engineer (LPCB or BAFE SP203-4 certificated)',
    evidenceRequired: 'Annual service certificate, and pump test results where a pump is fitted',
    handledBy: 'maintenance',
    handlingNote: 'Insurance usually requires the LPC pass certificate as well as the service report.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a sprinkler or other fixed suppression system',
  }),
  entry({
    key: 'dry_riser_annual_test',
    name: 'Dry riser — annual pressure test',
    description: 'Annual wet pressure test of the riser main, landing valves and inlet breeching.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 9990, annual test',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Riser service contractor',
    competencyRequired: 'Competent dry riser engineer',
    evidenceRequired: 'Annual test certificate recording pressure held and duration',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a dry (or wet) riser',
  }),
  entry({
    key: 'dry_riser_visual',
    name: 'Dry riser — six-monthly visual inspection',
    description: 'Visual inspection of inlets, outlets, cabinets and padlocks between annual tests.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 9990, six-monthly visual inspection',
    intervalBasis: 'stated',
    frequencyDays: 182,
    maxIntervalDays: 183,
    responsibleParty: 'Responsible person or riser contractor',
    competencyRequired: 'Briefed site staff or riser engineer',
    evidenceRequired: 'Inspection record noting condition and any missing components',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a dry (or wet) riser',
  }),
  entry({
    key: 'extinguishers_annual_service',
    name: 'Fire extinguishers — annual basic service',
    description: 'Basic service of every portable extinguisher by a competent technician.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS 5306-3, basic service',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Extinguisher service contractor',
    competencyRequired: 'Competent extinguisher technician (BAFE SP101 registered)',
    evidenceRequired: 'Service certificate and per-unit service labels',
    handledBy: 'maintenance',
    handlingNote: 'Absent from the Lancaster register — worth feeding back to its author.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has portable fire extinguishers in the common parts',
  }),
  entry({
    key: 'smoke_control_service',
    name: 'Smoke control / AOV system — service',
    description: 'Service and functional test of the smoke control system, including AOVs and any smoke shafts.',
    group: 'fire_safety',
    basis: 'standard',
    statutoryRef: 'BS EN 12101 / BS 7346-8, periodic servicing',
    intervalBasis: 'practice',
    frequencyDays: 182,
    maxIntervalDays: 366,
    responsibleParty: 'Smoke control contractor',
    competencyRequired: 'Competent smoke control engineer (Smoke Control Association member firm recommended)',
    evidenceRequired: 'Service certificate recording each vent and control panel tested',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a smoke control system, smoke shaft or automatic opening vents',
  }),
  entry({
    key: 'fser_monthly_equipment_check',
    name: 'Monthly check — firefighting equipment and facilities',
    description:
      'Monthly check of firefighting lifts, evacuation lifts and other firefighting equipment and facilities. '
      + 'A fault that cannot be fixed within 24 hours must be reported to the fire and rescue authority.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 6',
    intervalBasis: 'stated',
    frequencyDays: 30,
    maxIntervalDays: 31,
    responsibleParty: 'Responsible person',
    competencyRequired: 'Competent person familiar with the installed equipment',
    evidenceRequired: 'Monthly check record; separate record of any 24-hour fault report to the fire and rescue authority',
    handledBy: 'inspection',
    handlingNote:
      '⚠ The 24-hour FAULT REPORT to the fire and rescue service has no home in the portal — '
      + 'it is an event-driven deadline, not a cycle. Still open.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building is over 11 metres (always true for an HRB)',
  }),
  entry({
    key: 'fser_wayfinding_signage',
    name: 'Wayfinding signage — check',
    description: 'Check wayfinding signage identifying floor and flat numbers is present, legible and visible in low light.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 8; BS ISO 7010',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Responsible person or site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Walk-around log per floor, with any missing or illegible signs',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'pib_monthly_check',
    name: 'Premises information box — monthly check',
    description: 'Check the box is present, secure and accessible, and that the lock works.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 11',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Responsible person or site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Monthly inspection log',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'pib_content_review',
    name: 'Premises information box — content review',
    description: 'Confirm the contents are current: the responsible person’s contact details and hard-copy floor plans.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 11',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Responsible person',
    competencyRequired: 'Person who can confirm the plans against the building as built',
    evidenceRequired: 'Content version record; superseded contents withdrawn',
    handledBy: 'golden_thread',
    handlingNote: 'The plans and contact sheet are controlled documents; the box holds the current version.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'frs_plans_current',
    name: 'Fire and rescue service plans — confirm current',
    description: 'Confirm the floor plans and building plan held by the fire and rescue service still reflect the building.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022 — information to the fire and rescue service',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Responsible person',
    competencyRequired: 'Person who can confirm the plans against the building as built',
    evidenceRequired: 'Record of the check and of any re-issue to the fire and rescue service',
    handledBy: 'building_assets',
    handlingNote: 'The plans themselves are Building Assets floor plans; re-issue is a manual step.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'resident_fire_safety_info',
    name: 'Fire safety instructions to residents — refresh',
    description: 'Re-issue the fire safety instructions and evacuation information to all residents.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Fire Safety (England) Regulations 2022, reg 4',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Responsible person',
    evidenceRequired: 'Distribution record and communications log; also issued to new residents on move-in',
    handledBy: 'info',
    handlingNote: 'Published through the Info app; per-resident issue on move-in has no home (resident data is out of scope).',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building is over 11 metres in height (always true for an HRB)',
  }),
  entry({
    key: 'escape_route_obstruction',
    name: 'Escape routes — obstruction check',
    description: 'Walk the escape routes and stair cores and clear anything obstructing them.',
    group: 'fire_safety',
    basis: 'statute',
    statutoryRef: 'Regulatory Reform (Fire Safety) Order 2005, art 14',
    intervalBasis: 'practice',
    frequencyDays: 7,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Walk-around log, with an exception report on anything found',
    handledBy: 'inspection',
    handlingNote: 'A single-staircase building should consider daily rather than weekly.',
    evidencedBy: 'inspection',
    appliesWhen: 'Always — art 14 applies wherever there are escape routes',
  }),
  entry({
    key: 'tabletop_fire_exercise',
    name: 'Tabletop fire exercise',
    description: 'Desktop exercise walking a fire scenario through with those who would have to act.',
    group: 'fire_safety',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports BSA 2022 s.84 reasonable steps',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Exercise log and lessons learned',
    handledBy: 'planner',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always — a cheap and well-regarded discipline',
  }),

  // ══ 2 · Other statutory checks ══════════════════════════════════════════
  entry({
    key: 'eicr_common_parts',
    name: 'EICR — common parts and landlord supply',
    description: 'Periodic inspection and testing of the common-parts electrical installation.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Electricity at Work Regulations 1989; BS 7671',
    intervalBasis: 'practice',
    frequencyDays: 1825,
    maxIntervalDays: 1826,
    responsibleParty: 'Electrical contractor',
    competencyRequired: 'Qualified electrician; NICEIC / NAPIT registered firm recommended',
    evidenceRequired: 'Electrical Installation Condition Report with observation codes and remedial actions',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a common-parts or landlord electrical supply (always true in practice)',
  }),
  entry({
    key: 'eicr_dwellings',
    name: 'EICR — rented dwellings',
    description: 'Five-yearly inspection and testing of the electrical installation in each rented dwelling.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Electrical Safety Standards in the Private Rented Sector (England) Regulations 2020, reg 3',
    intervalBasis: 'stated',
    frequencyDays: 1825,
    maxIntervalDays: 1826,
    responsibleParty: 'Electrical contractor',
    competencyRequired: 'Qualified and competent electrician',
    evidenceRequired: 'EICR per dwelling; copy to the tenant within 28 days',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Any dwelling is let on a relevant tenancy — long leases alone do NOT trigger this',
  }),
  entry({
    key: 'communal_electrics_visual',
    name: 'Communal electrics — annual visual inspection',
    description: 'Visual inspection of communal electrical installations between full EICRs.',
    group: 'other_statutory',
    basis: 'standard',
    statutoryRef: 'IET Code of Practice',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Managing agent',
    competencyRequired: 'Competent person',
    evidenceRequired: 'Inspection log',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has communal electrical installations',
  }),
  entry({
    key: 'pat_testing',
    name: 'Portable appliance testing',
    description: 'In-service inspection and testing of portable appliances in the common parts.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Provision and Use of Work Equipment Regulations 1998; IET Code of Practice',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Managing agent',
    competencyRequired: 'Competent person for in-service testing',
    evidenceRequired: 'PAT log per appliance',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'There are portable appliances in the common parts — concierge desk, communal kitchen, plant room',
  }),
  entry({
    key: 'gas_safety_check',
    name: 'Gas safety check',
    description: 'Annual safety check of gas appliances and flues for which the landlord is responsible.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Gas Safety (Installation and Use) Regulations 1998, reg 36(3)',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Gas Safe registered engineer',
    competencyRequired: 'Gas Safe registered, with the correct appliance categories',
    evidenceRequired: 'Landlord gas safety record (CP12); copy to each affected tenant',
    retentionPeriodMonths: 24,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Landlord is responsible for any gas appliance, flue or pipework — confirm there is a communal supply',
  }),
  entry({
    key: 'lift_loler_examination',
    name: 'Lift — LOLER thorough examination',
    description: 'Thorough examination of each passenger lift by a competent person.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Lifting Operations and Lifting Equipment Regulations 1998, reg 9(3)',
    intervalBasis: 'stated',
    frequencyDays: 182,
    maxIntervalDays: 183,
    responsibleParty: 'Insurance inspection body or independent examiner',
    competencyRequired:
      'Competent person INDEPENDENT of the maintenance contractor — a lift service visit is not a thorough examination',
    evidenceRequired: 'Report of thorough examination, with any defect notified to the duty holder',
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a lift carrying people',
  }),
  entry({
    key: 'lift_maintenance',
    name: 'Lift — routine maintenance service',
    description: 'Routine preventive maintenance visit under the lift service contract.',
    group: 'other_statutory',
    basis: 'contract',
    statutoryRef: 'PUWER 1998; BS EN 13015; manufacturer recommendations',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Lift maintenance contractor',
    competencyRequired: 'Competent lift engineer',
    evidenceRequired: 'Service visit report / lift logbook entry',
    handledBy: 'maintenance',
    handlingNote: 'Monthly is typical; the binding interval is whatever the service contract says.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a lift',
  }),
  entry({
    key: 'water_temperature_monitoring',
    name: 'Water temperature monitoring',
    description: 'Routine monitoring of hot and cold water temperatures at sentinel outlets.',
    group: 'other_statutory',
    basis: 'standard',
    statutoryRef: 'HSE ACOP L8 / HSG274 Part 2, routine monitoring',
    intervalBasis: 'practice',
    frequencyDays: 30,
    maxIntervalDays: 31,
    responsibleParty: 'Site staff or water hygiene contractor',
    competencyRequired: 'Briefed staff working to the written control scheme',
    evidenceRequired: 'Monitoring log with temperatures and outlets, and action on out-of-range readings',
    retentionPeriodMonths: 60,
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a communal hot or cold water system',
  }),
  entry({
    key: 'legionella_risk_review',
    name: 'Legionella risk assessment — review',
    description: 'Review the water system risk assessment and confirm the written control scheme is still valid.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Health and Safety at Work etc. Act 1974 / COSHH, via ACOP L8 and HSG274',
    intervalBasis: 'practice',
    frequencyDays: 730,
    responsibleParty: 'Duty holder, via a competent water hygiene assessor',
    competencyRequired: 'Competent legionella risk assessor (Legionella Control Association registered)',
    evidenceRequired: 'Reviewed risk assessment and written control scheme',
    retentionPeriodMonths: 60,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a water system the duty holder controls — communal tanks or boosted mains',
  }),
  entry({
    key: 'water_tank_inspection',
    name: 'Water tanks — inspection and clean',
    description: 'Inspect and, where required, clean and disinfect cold water storage tanks.',
    group: 'other_statutory',
    basis: 'standard',
    statutoryRef: 'HSE ACOP L8 / HSG274 Part 2',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Water hygiene contractor',
    competencyRequired: 'Competent water hygiene technician',
    evidenceRequired: 'Inspection report; cleaning and disinfection certificate where carried out',
    retentionPeriodMonths: 60,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has cold water storage tanks',
  }),
  entry({
    key: 'asbestos_reinspection',
    name: 'Asbestos — re-inspection',
    description: 'Re-inspect known and presumed asbestos-containing materials and update the register.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Control of Asbestos Regulations 2012, reg 4',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Asbestos surveyor',
    competencyRequired: 'Competent asbestos surveyor',
    evidenceRequired: 'Re-inspection report and an updated asbestos register',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    handlingNote: 'The duty to manage is continuous; the register is the artefact the safety case needs.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building may contain asbestos — anything built or refurbished before 2000',
  }),
  entry({
    key: 'asbestos_register_on_works',
    name: 'Asbestos register — check before works',
    description: 'Consult and annotate the asbestos register before any work that could disturb the fabric.',
    group: 'other_statutory',
    basis: 'statute',
    statutoryRef: 'Control of Asbestos Regulations 2012, reg 4',
    intervalBasis: 'stated',
    trigger: 'Before every intrusive work order or disturbance of the fabric',
    responsibleParty: 'Managing agent',
    competencyRequired: 'Person raising the works order',
    evidenceRequired: 'Register annotation and a method statement reference on the works order',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote:
      '⚠ No home. Event-driven, not a cycle — it belongs on the Works Schedules flow as a pre-issue check.',
    evidencedBy: null,
    appliesWhen: 'Building may contain asbestos and works are ever carried out',
  }),
  entry({
    key: 'lightning_protection',
    name: 'Lightning protection — test and inspection',
    description: 'Inspection and earth-resistance testing of the lightning protection system.',
    group: 'other_statutory',
    basis: 'standard',
    statutoryRef: 'BS EN 62305-3, periodic inspection and testing',
    intervalBasis: 'stated',
    frequencyDays: 365,
    maxIntervalDays: 366,
    responsibleParty: 'Lightning protection contractor',
    competencyRequired: 'Competent lightning protection engineer (ATLAS member firm recommended)',
    evidenceRequired: 'Test certificate recording earth resistance readings per down conductor',
    retentionPeriodMonths: 60,
    handledBy: 'maintenance',
    handlingNote: 'Often run on an 11-month rolling cycle so the test season varies year to year.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Building has a lightning protection system — confirm whether one is installed',
  }),
  entry({
    key: 'structural_inspection',
    name: 'Structural inspection — visual',
    description: 'Visual structural inspection by a structural engineer or competent surveyor.',
    group: 'other_statutory',
    basis: 'management',
    statutoryRef: 'Self-imposed',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Structural engineer or competent surveyor',
    competencyRequired: 'Chartered structural engineer for anything beyond a visual walk',
    evidenceRequired: 'Inspection report',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    handlingNote: 'A building with known structural concerns needs a shorter interim cycle until it is fixed.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB; more often where there are known structural findings',
  }),
  entry({
    key: 'roof_facade_check',
    name: 'Roof and façade — visual check',
    description: 'Visual check of roof and façade condition, repeated after any severe weather.',
    group: 'other_statutory',
    basis: 'management',
    statutoryRef: 'Self-imposed',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Managing agent',
    evidenceRequired: 'Walk-around report with photographs',
    handledBy: 'maintenance',
    handlingNote: 'Also triggered by storms — the calendar cycle is the floor, not the whole duty.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),
  entry({
    key: 'drainage_gutter_clearance',
    name: 'Drainage and gutter clearance',
    description: 'Clear gutters, hoppers and drainage runs.',
    group: 'other_statutory',
    basis: 'contract',
    statutoryRef: 'Maintenance contract',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Managing agent',
    evidenceRequired: 'Service record',
    retentionPeriodMonths: 24,
    handledBy: 'maintenance',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),

  // ══ 3 · BSA-specific cycles ═════════════════════════════════════════════
  entry({
    key: 'scr_review',
    name: 'Safety case report — review',
    description: 'Full review of the safety case report, recording “no material change” where that is the finding.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.83',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Reviewed safety case report and the review record',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'The Safety Case tab builds the report on demand; migration 202 logs each revision.',
    evidencedBy: null,
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'scr_resubmission',
    name: 'Safety case report — notify the regulator of a revision',
    description: 'Notify the BSR when the safety case report is revised, and record the reference given.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.86',
    intervalBasis: 'stated',
    trigger: 'On material change, or on BSR direction',
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'BSR receipt and the safety case version record',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'Built: the s.86 notification log (migration 202) — pending until marked notified.',
    evidencedBy: null,
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'kbi_update',
    name: 'Key building information — review',
    description: 'Review the key building information held by the regulator and resubmit on change.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Higher-Risk Buildings (Keeping and Provision of Information etc.) Regs 2024 (SI 2024/41), reg 5',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'KBI submission record',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home. KBI is not modelled anywhere in the portal.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'bac_renewal',
    name: 'Building assessment certificate — renewal',
    description: 'Track the building assessment certificate and its renewal or re-direction by the regulator.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.86',
    intervalBasis: 'practice',
    frequencyDays: 1825,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'BAC certificate and BSR correspondence',
    retentionPeriodMonths: 120,
    handledBy: 'admin',
    handlingNote: 'The BAC is one of the s.82 display register’s guaranteed slots.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'reasonable_steps_register_review',
    name: 'Reasonable steps register — review',
    description: 'Review the record of reasonable steps taken to manage building safety risks.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.84',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Reviewed register and meeting minutes',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home. Closest thing is the Golden Thread risk register, which is not the same artefact.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'persons_register_review',
    name: 'Competence register — review',
    description: 'Review each person’s competence record, limitations and reassessment triggers.',
    group: 'bsa_cycle',
    basis: 'management',
    statutoryRef: 'Self-imposed; competence under BS 8670',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Updated competence register entries',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'Built: gt_persons, with limitations / supervision / reassessment triggers (migration 201).',
    evidencedBy: null,
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'gt_register_audit',
    name: 'Golden Thread document register — audit',
    description: 'Audit the document register for completeness, currency and correct classification.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Higher-Risk Buildings (Keeping and Provision of Information etc.) Regs 2024 (SI 2024/41)',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Information manager',
    evidenceRequired: 'Register audit report',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'gt_cyclical_document_review',
    name: 'Golden Thread — per-document review cycle',
    description: 'Each controlled document reaches its own review date and is confirmed, revised or superseded.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Higher-Risk Buildings (Keeping and Provision of Information etc.) Regs 2024 (SI 2024/41), reg 6',
    intervalBasis: 'practice',
    trigger: 'Each document’s own review date',
    responsibleParty: 'Information manager',
    evidenceRequired: 'Per-document supersession records',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'Built: gtReview.js computes review-due per document. Not a single building-wide cycle.',
    evidencedBy: null,
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'audit_chain_verification',
    name: 'Audit chain — verification',
    description: 'Verify the hash-chained audit log has not been altered.',
    group: 'bsa_cycle',
    basis: 'management',
    statutoryRef: 'Self-imposed; safety case integrity',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Information manager',
    evidenceRequired: 'Verification result log',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'Built: /api/golden-thread/verify-audit. Run on demand — no scheduled run exists.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'mor_open_case_review',
    name: 'MOR — open case review',
    description: 'Review every open mandatory occurrence report against its statutory clocks.',
    group: 'bsa_cycle',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports the s.87 reporting duties',
    intervalBasis: 'practice',
    frequencyDays: 7,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Review log and case timeline notes',
    retentionPeriodMonths: 120,
    handledBy: 'mor',
    handlingNote: 'The MOR app tracks the clocks per case; this is the recurring look at all of them.',
    evidencedBy: null,
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'mor_lessons_learned',
    name: 'MOR — closed case review (lessons learned)',
    description: 'Review closed occurrences for systemic causes and revise procedures where indicated.',
    group: 'bsa_cycle',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports BSA 2022 s.84 reasonable steps',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Meeting minutes and revised procedures',
    retentionPeriodMonths: 120,
    handledBy: 'mor',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'mor_system_effectiveness_review',
    name: 'MOR system — effectiveness review',
    description: 'Review the mandatory occurrence reporting system itself, to confirm it remains effective and accessible.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Higher-Risk Buildings (Management of Safety Risks etc.) Regs 2023 (SI 2023/907), reg 6(4)',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Review record covering accessibility to residents and other users',
    retentionPeriodMonths: 120,
    handledBy: 'mor',
    handlingNote: 'A duty on the SYSTEM, not on a case — surfaced by BSA_V2_Mapping.md EXT-12.R1.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'complaints_self_assessment',
    name: 'Complaints — annual performance self-assessment',
    description: 'Self-assess complaint handling against the Complaint Handling Code.',
    group: 'bsa_cycle',
    basis: 'standard',
    statutoryRef: 'Housing Ombudsman Complaint Handling Code 2024',
    intervalBasis: 'stated',
    frequencyDays: 365,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Completed self-assessment',
    retentionPeriodMonths: 120,
    handledBy: 'complaints',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),
  entry({
    key: 'complaints_report_publication',
    name: 'Complaints — annual performance report',
    description: 'Publish the annual complaints performance report to residents.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Higher-Risk Buildings (Management of Safety Risks etc.) Regs 2023 (SI 2023/909), reg 12',
    intervalBasis: 'stated',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Published report and the resident communications record',
    retentionPeriodMonths: 120,
    handledBy: 'complaints',
    handlingNote: 'The Complaints app holds the cases; the report itself is not generated yet.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),
  entry({
    key: 'res_strategy_review',
    name: 'Residents’ engagement strategy — review',
    description: 'Review the residents’ engagement strategy, at least every two years.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.91; SI 2023/907 reg 11',
    intervalBasis: 'stated',
    frequencyDays: 730,
    maxIntervalDays: 730,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Reviewed strategy and the engagement record',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home. Also triggered by a submitted MOR and by significant alterations.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'res_consultation',
    name: 'Residents’ engagement — consultation on a building safety decision',
    description: 'Consult residents on a building safety decision, for no less than three weeks.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.91; SI 2023/907 reg 10',
    intervalBasis: 'stated',
    trigger: 'Per building safety decision requiring consultation',
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Consultation record and a “you said, we did” response',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home. The three-week minimum is statutory and must not be closable early.',
    evidencedBy: null,
    appliesWhen: 'A building safety decision affecting residents is taken',
  }),
  entry({
    key: 'res_bulletin',
    name: 'Residents’ safety bulletin',
    description: 'Regular safety bulletin to residents.',
    group: 'bsa_cycle',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports the engagement strategy',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Issued bulletin and readership record',
    retentionPeriodMonths: 36,
    handledBy: 'info',
    handlingNote: 'The Info app publishes to residents; readership is not measured.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),
  entry({
    key: 'engagement_effectiveness',
    name: 'Engagement effectiveness — measurement',
    description: 'Measure and report whether resident engagement is actually working.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.91(3)(d)',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Effectiveness report',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'contractor_certification_refresh',
    name: 'Approved contractors — certification refresh',
    description: 'Confirm each approved contractor’s scheme certification and insurance are still in date.',
    group: 'bsa_cycle',
    basis: 'contract',
    statutoryRef: 'Self-imposed; insurance-driven',
    intervalBasis: 'practice',
    trigger: 'Per certificate expiry',
    responsibleParty: 'Managing agent procurement',
    evidenceRequired: 'Refreshed register entries with certificate copies',
    handledBy: 'none',
    handlingNote: '⚠ No home. Contractors exist as profiles; their certification is not tracked.',
    evidencedBy: null,
    appliesWhen: 'Contractors are engaged on safety-critical work',
  }),
  entry({
    key: 'cooperation_arrangements_review',
    name: 'Cooperation arrangements — review',
    description: 'Review the arrangements for cooperation between accountable persons and other duty holders.',
    group: 'bsa_cycle',
    basis: 'statute',
    statutoryRef: 'Building Safety Act 2022, s.156',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Reviewed cooperation arrangement document',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    handlingNote: 'The AP register records who is accountable for which part (migration 201).',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'There is more than one accountable person, or a duty holder changes',
  }),

  // ══ 4 · Governance and review cycles ════════════════════════════════════
  entry({
    key: 'board_safety_standing_item',
    name: 'Board meeting — building safety standing item',
    description: 'Building safety as a standing item on the board agenda.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed; demonstrates accountability',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Directors collectively',
    evidenceRequired: 'Board minutes',
    retentionPeriodMonths: 120,
    handledBy: 'management',
    handlingNote: 'Meetings and minutes live in the Management app.',
    evidencedBy: null,
    appliesWhen: 'Always',
  }),
  entry({
    key: 'quarterly_safety_review',
    name: 'Quarterly safety review',
    description: 'Operational review of what is open and what is closing — the first line of assurance.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed (three-line assurance model)',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Building safety lead with the managing agent',
    evidenceRequired: 'Meeting record and action register update',
    retentionPeriodMonths: 120,
    handledBy: 'management',
    evidencedBy: null,
    appliesWhen: 'Always',
  }),
  entry({
    key: 'annual_safety_case_review',
    name: 'Annual safety case review (full)',
    description: 'Governance review of whether the operational picture still supports the safety case as a whole.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed (second line); supports BSA 2022 s.83',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person with an independent reviewer',
    evidenceRequired: 'Review report; safety case update where there is material change',
    retentionPeriodMonths: 120,
    handledBy: 'golden_thread',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always for an HRB',
  }),
  entry({
    key: 'external_audit',
    name: 'External audit — third-line assurance',
    description: 'Independent check that what is being claimed is what is actually happening.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed (three-line assurance model)',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person, commissioned externally',
    competencyRequired: 'Competent third party independent of the operation',
    evidenceRequired: 'External audit report',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote: '⚠ No home. No legal duty requires it in this form; it is what makes the case defensible.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always — recommended, not required',
  }),
  entry({
    key: 'agm_safety_report',
    name: 'Annual residents’ safety meeting / AGM safety report',
    description: 'Report on building safety to residents at the AGM or an equivalent meeting.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports the engagement strategy',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Meeting record and AGM minutes',
    retentionPeriodMonths: 120,
    handledBy: 'planner',
    handlingNote: 'The AGM is exactly the kind of expected annual event the Planner exists for.',
    evidencedBy: null,
    appliesWhen: 'Always',
  }),
  entry({
    key: 'insurance_renewal_briefing',
    name: 'Insurance renewal — safety case briefing',
    description: 'Brief the insurer or broker on the building safety position at renewal.',
    group: 'governance',
    basis: 'contract',
    statutoryRef: 'Insurer requirement',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person with the broker',
    evidenceRequired: 'Renewal briefing pack',
    retentionPeriodMonths: 84,
    handledBy: 'planner',
    handlingNote: 'Insurance renewal is a Planner event; the briefing pack is not produced by the portal.',
    evidencedBy: null,
    appliesWhen: 'Always',
  }),
  entry({
    key: 'bsl_performance_review',
    name: 'Building safety lead — performance review',
    description: 'Annual review of the named building safety lead’s performance and continued competence.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Review record',
    retentionPeriodMonths: 84,
    handledBy: 'none',
    handlingNote: '⚠ No home, and it should probably stay that way — it is an HR record, not a building record.',
    evidencedBy: null,
    appliesWhen: 'A building safety lead has been appointed',
  }),
  entry({
    key: 'regulator_informal_contact',
    name: 'Regulator — informal contact',
    description: 'Keep a line open to the Building Safety Regulator outside formal submissions.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed; no statutory requirement',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Correspondence log',
    retentionPeriodMonths: 84,
    handledBy: 'none',
    handlingNote: '⚠ No home.',
    evidencedBy: null,
    appliesWhen: 'Always — optional discipline',
  }),
  // ══ 5 · Building-specific cycles ════════════════════════════════════════
  // Cycles this building needs because of its own characteristics and its own
  // open findings — a single staircase with no smoke ventilation, and the
  // basement structural concerns. From BSA_Periodic_Activities_and_Checks §5.
  //
  // These are the items that distinguish this building's safety case from a
  // generic one, so they belong in the register — but several are INTERIM,
  // running only until a permanent fix lands. When one does, the honest move is
  // to record an 'applicable' → excluded decision with the fix as the reason,
  // not to quietly delete the entry.
  entry({
    key: 'acrow_prop_check',
    name: 'Acrow props — position and integrity check',
    description: 'Check the temporary props supporting the basement mezzanine are in position, plumb and undamaged.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed; structural engineer recommendation pending permanent fix',
    intervalBasis: 'practice',
    frequencyDays: 7,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff; anything found escalates to the structural engineer',
    evidenceRequired: 'Inspection log with photographs',
    retentionPeriodMonths: 120,
    handledBy: 'inspection',
    handlingNote:
      'INTERIM — runs until the permanent structural fix is delivered and certified. '
      + 'The single most important operational discipline in the building while the props are in place.',
    evidencedBy: 'inspection',
    appliesWhen: 'Temporary propping is in place anywhere in the building',
  }),
  entry({
    key: 'cracked_column_check',
    name: 'Cracked columns — visual check',
    description: 'Visual check of the cracked mezzanine columns and rusting beams against comparison photographs.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed pending permanent fix',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Structural engineer or competent surveyor',
    competencyRequired: 'Competent surveyor; a chartered structural engineer for any change found',
    evidenceRequired: 'Inspection report with comparison photographs',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    handlingNote: 'INTERIM — until the permanent structural fix is delivered.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'There are known structural defects under monitoring',
  }),
  entry({
    key: 'crack_monitoring',
    name: 'Crack monitoring — telltales or strain gauges',
    description: 'Read and record any crack monitoring devices fitted, at the interval the device specification sets.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed; structural engineer specification',
    intervalBasis: 'practice',
    trigger: 'The interval set by the monitoring device specification',
    responsibleParty: 'Structural engineer or their appointed monitor',
    evidenceRequired: 'Monitoring data series',
    retentionPeriodMonths: 120,
    handledBy: 'none',
    handlingNote:
      '⚠ No home. A reading series is measurement data, not a pass/fail check — the closest fit is the '
      + 'inspection `readings` jsonb (migration 169), which nothing currently drives on a schedule.',
    evidencedBy: null,
    appliesWhen: 'Crack monitoring devices have been fitted',
  }),
  entry({
    key: 'structural_interim_review',
    name: 'Structural engineer — interim review',
    description: 'Engineer reviews the monitoring record and confirms the interim measures remain adequate.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed pending permanent fix',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Structural engineer',
    competencyRequired: 'Chartered structural engineer',
    evidenceRequired: 'Engineer review report',
    retentionPeriodMonths: 120,
    handledBy: 'maintenance',
    handlingNote: 'INTERIM — reverts to the annual structural inspection once the permanent fix is certified.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Interim structural measures are in place',
  }),
  entry({
    key: 'stair_core_walk_around',
    name: 'Stair core — walk-around',
    description: 'Walk the stair core end to end, looking for anything that compromises the protected route.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed; protection of the single protected route',
    intervalBasis: 'practice',
    frequencyDays: 1,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Walk-around log, with an exception report on anything found',
    handledBy: 'inspection',
    handlingNote:
      'A single-staircase building with simultaneous evacuation and no smoke ventilation has one protected '
      + 'route and no second chance — which is why this is daily rather than weekly.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a single staircase',
  }),
  entry({
    key: 'lobby_to_stair_door_check',
    name: 'Lobby-to-stair doors — visual check',
    description: 'Visual check of the doors protecting the stair core, between the quarterly full door rounds.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed; supplements the quarterly fire door round',
    intervalBasis: 'practice',
    frequencyDays: 7,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Visual check log',
    handledBy: 'inspection',
    handlingNote: 'A single staircase makes these doors disproportionately important; cadence is open to review.',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a single staircase protected by fire doors',
  }),
  entry({
    key: 'stair_lighting_check',
    name: 'Stair lighting — check',
    description: 'Check normal and emergency lighting in the stair core is working.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed; supplements BS 5266 monthly testing',
    intervalBasis: 'practice',
    frequencyDays: 7,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Walk-around log',
    handledBy: 'inspection',
    evidencedBy: 'inspection',
    appliesWhen: 'Building has a single staircase',
  }),
  entry({
    key: 'alarm_coverage_gap_monitoring',
    name: 'Fire alarm coverage — gap monitoring',
    description: 'Review the open action to establish fire alarm coverage, and age it.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed pending a coverage assessment',
    intervalBasis: 'practice',
    frequencyDays: 30,
    responsibleParty: 'Building safety lead',
    evidenceRequired: 'Review log and the ageing of the open action',
    retentionPeriodMonths: 120,
    handledBy: 'management',
    handlingNote:
      'INTERIM — until the coverage report lands. Where coverage is unknown, the safety case has a gap about '
      + 'what is NOT in scope of the six-monthly service, which is the thing being monitored.',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Fire alarm coverage has not been established by survey',
  }),
  entry({
    key: 'alarm_audibility_spot_check',
    name: 'Fire alarm audibility — per-floor spot check',
    description: 'Spot-check audibility on each floor during the alarm test.',
    group: 'building_specific',
    basis: 'management',
    statutoryRef: 'Self-imposed pending a coverage assessment',
    intervalBasis: 'practice',
    frequencyDays: 90,
    responsibleParty: 'Site staff',
    competencyRequired: 'Briefed site staff',
    evidenceRequired: 'Spot-check log per floor',
    handledBy: 'inspection',
    handlingNote: 'INTERIM — a partial substitute for a proper coverage assessment, not a replacement for one.',
    evidencedBy: 'inspection',
    appliesWhen: 'Fire alarm coverage has not been established by survey',
  }),

  entry({
    key: 'leaseholder_safety_update',
    name: 'Leaseholder safety update',
    description: 'Written update to leaseholders on the building safety position.',
    group: 'governance',
    basis: 'management',
    statutoryRef: 'Self-imposed; supports the engagement strategy',
    intervalBasis: 'practice',
    frequencyDays: 365,
    responsibleParty: 'Principal accountable person',
    evidenceRequired: 'Communication issued; readership record',
    retentionPeriodMonths: 84,
    handledBy: 'info',
    evidencedBy: 'maintenance_job',
    appliesWhen: 'Always',
  }),
];
