// src/lib/server/gtSharePack.js
//
// Pure helpers for the Golden Thread BSR share pack: filename safety, in-pack
// paths, the manifest object, and the human-readable README. No I/O — the
// endpoint (/api/golden-thread/share-pack) does the DB reads + file streaming
// and calls these, so the shaping logic stays unit-testable.

const UNSAFE_PATH_CHARS = /[/\\:*?"<>|]/g;   // path separators; keep spaces/hyphens

/** Replace characters unsafe in a zip entry path segment. */
export function sanitizeName(s) {
  const cleaned = String(s ?? '')
    .replace(UNSAFE_PATH_CHARS, '_')
    .replace(/^\.+/, '_')                 // no leading dots
    .trim();
  return cleaned || 'file';
}

/**
 * In-pack path for a document's file: `files/<reference>/<filename>`, with a
 * `(n)` suffix if a document has more than one file of the same name. `seen`
 * is a Set the caller threads across all files to keep names unique.
 * @param {string} reference
 * @param {string} filename
 * @param {Set<string>} seen
 * @returns {string}
 */
export function packPath(reference, filename, seen) {
  const dir  = sanitizeName(reference);
  const base = sanitizeName(filename);
  let name = `files/${dir}/${base}`;
  if (seen.has(name)) {
    const dot  = base.lastIndexOf('.');
    const stem = dot > 0 ? base.slice(0, dot) : base;
    const ext  = dot > 0 ? base.slice(dot) : '';
    let i = 2;
    do { name = `files/${dir}/${stem} (${i})${ext}`; i++; } while (seen.has(name));
  }
  seen.add(name);
  return name;
}

/**
 * Build the machine-readable manifest for the pack.
 * @param {object} args
 * @param {string} args.generatedAt  ISO timestamp
 * @param {string} args.generatedBy  user email
 * @param {Array<{document: object, files: Array}>} args.documents
 * @param {Array<{code:number,name:string,currentCount:number,satisfied:boolean}>} [args.completeness]
 */
export function buildManifest({ generatedAt, generatedBy, documents, completeness = [] }) {
  const allFiles   = documents.flatMap((d) => d.files);
  const mismatches = allFiles.filter((f) => f.checksum_ok === false).length;
  const missing    = documents.filter((d) => d.files.length === 0).length;
  return {
    kind: 'golden_thread_bsr_share_pack',
    version: 1,
    generated_at: generatedAt,
    generated_by: generatedBy,
    document_count: documents.length,
    file_count: allFiles.length,
    integrity: {
      checksum_algorithm: 'sha256',
      checksum_mismatches: mismatches,
      documents_without_file: missing,
    },
    completeness,
    documents: documents.map(({ document: d, files }) => ({
      reference: d.reference,
      title: d.title,
      document_type: d.document_type,
      schedule1_category: d.schedule1_category,
      status: d.status,
      effective_from: d.effective_from ?? null,
      review_due: d.review_due ?? null,
      safety_critical: !!d.safety_critical,
      files,
    })),
  };
}

/** Human-readable README text for the pack. */
export function renderReadme(m) {
  const lines = [
    'GOLDEN THREAD — BSR SHARE PACK',
    '================================',
    '',
    `Generated:    ${m.generated_at}`,
    `Generated by: ${m.generated_by}`,
    `Documents:    ${m.document_count} (current register documents)`,
    `Files:        ${m.file_count}`,
    `Integrity:    SHA-256; ${m.integrity.checksum_mismatches} checksum mismatch(es), `
      + `${m.integrity.documents_without_file} document(s) with no file`,
    '',
    'Contents:',
    '  manifest.json  — machine-readable index of every document and file, with',
    '                   stored vs recomputed SHA-256 checksums for integrity.',
    '  files/<ref>/…  — the document files, one folder per register reference.',
    '',
    'Documents in this pack:',
    ...m.documents.map((d) => `  ${d.reference}  ${d.title}  [${d.status}]`),
    '',
  ];
  if (m.completeness?.length) {
    lines.push('Schedule-1 completeness (applicable categories):');
    for (const c of m.completeness) {
      lines.push(`  ${String(c.code).padStart(2)} ${c.satisfied ? '[ok]     ' : '[MISSING]'} ${c.name} (${c.currentCount})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
